### ISSUE TITLE
ActivityPub object is served with incorrect content type

### ISSUE THREAD

**Issue by silverpill** [llun/activities.next#70]
Hello, I encountered the following problem with llun.dev server. Assuming that server runs this software.

When retrieving ActivityPub object, I get a response with `content-type: application/json` header:

```
curl -v -H 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"' https://llun.dev/users/null/statuses/2bf9c327-71b0-498c-856c-9225c4138cdf
...
< HTTP/2 200 
< content-type: application/json
```

However, for security reasons, some clients may expect the content type to be either `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` or `application/activity+json`. In the past several projects were vulnerable to an impersonation attack due to a lack of such validation; attacker was able to upload malicious ActivityPub object as media, and thus bypass the same-origin check.

**Comment by llun** [comment]
Hi @silverpill, thanks for reporting this. Just want to clarify the issue. So, the request has a header with Accept `application/ld+json; profile="https://www.w3.org/ns/activitysteams"` and you expect the server to response back with the same content type `application/ld+json` or `application/activity+json` right? but currently the server response back with content type `application/json`.

**Comment by silverpill** [comment]
Yes, I'd expect one of the two media types mentioned in ActivityPub spec: https://www.w3.org/TR/activitypub/#retrieving-objects

**Comment by llun** [comment]
@silverpill I updated the api to only response to those accept header. This should be fixed now.

**Comment by silverpill** [comment]
Thanks for looking into it @llun

The post seems to be OK, but the actor object (https://llun.dev/users/null) is still served as `application/json`.

Also, am I understanding it correctly that you now only serve AP object if the value of `Accept` header is `application/ld+json; profile="https://www.w3.org/ns/activitystreams"`, and redirect to HTML page otherwise?
While that works for me, and is correct according to the ActivityPub spec, this is not reliable. Many implementations use different value, for example Pleroma uses `Accept: application/activity+json` and (according to my notes) Mastodon uses `Accept: application/activity+json; q=0.9, application/ld+json;profile=\x22https://www.w3.org/ns/activitystreams\x22; q=0.8, text/html; charset=utf-8; q=0.7`

**Comment by silverpill** [comment]
It's working. Thank you @llun
